### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by sameerd** [ranganathanlab/bmDCA#4]
These lines should refer to `arma_convert` and not `bmdca_sample`

https://github.com/ranganathanlab/bmDCA/blob/096ec59eabdf9f81b58e121f1b4ff62694ac5f51/src/arma_convert.cpp#L13-L16

**Comment by sudorook** [comment]
Fixed in 056a632febdef62d5ef80a0e6e4815949a0ad392
